
@startuml "Context Diagram"

Actor Owner
Actor Employee
Actor Customer
Actor Supplier

Actor Printer

usecase EZShop

Employee -right- EZShop
Owner -up-|> Employee

EZShop -right-> Customer
EZShop -right-> Supplier
EZShop -up-> Printer

@enduml